language: c

matrix:
  include:
    - name: "haxm-darwin"
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
            - nasm
      script:
        - cd platforms/darwin
        - xcodebuild -configuration Debug -sdk macosx10.14

    - name: "haxm-linux"
      os: linux
      dist: trusty
      sudo: false
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y linux-headers-`uname -r`
        - wget http://mirrors.kernel.org/ubuntu/pool/universe/n/nasm/nasm_2.13.02-0.1_amd64.deb
        - sudo apt-get install -y dpkg
        - sudo dpkg -i nasm_2.13.02-0.1_amd64.deb
      script:
        - cd platforms/linux
        - make -j$(nproc)

  exclude: # TODO: Currently TravisCI does not support full VS/EWDK on Windows
    - name: "haxm-windows"
      os: windows
      install:
        - choco install -y nuget.commandline
        - choco install -y windowsdriverkit10
      script:
        - cd platforms/windows
        - nuget restore
        - export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/Installer/"
        - export MSVC=$(vswhere -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath)
        - export MSVC=$(echo /$MSVC | sed -e 's/\\/\//g' -e 's/://')
        - export PATH="$PATH:$MSVC/MSBuild/15.0/Bin/"
        - MSBuild.exe haxm.sln //p:Configuration="Debug" //p:Platform="x64"
