name: HAXM build on Windows

on: [push, pull_request]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  my_first_job:
    name: Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: Install related pkg
      run: |
        choco install -y nuget.commandline
        choco install -y windowsdriverkit10
        choco install -y windows-sdk-8.1
    - name: Build
      run: |
        cd platforms/windows
        nuget restore
        msbuild haxm.sln /p:Configuration="Debug" /p:Platform="Win32"
        msbuild haxm.sln /p:Configuration="Debug" /p:Platform="x64"
        ./build/tests/x64/Debug/haxm-tests.exe
